AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    7aafd357-fcf3-4660-b207-84b6cc696b0c:
      size:
        width: 60
        height: 60
      position:
        x: 310
        'y': 70
      z: 0
      embeds: []
      dependson:
        - c0fc79f2-0397-4704-9841-48453b668bb4
    c0fc79f2-0397-4704-9841-48453b668bb4:
      size:
        width: 60
        height: 60
      position:
        x: 430
        'y': 20
      z: 0
      embeds: []
Resources:
  BucketHost:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
        - "-"
        - - "mfe-react"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      WebsiteConfiguration:
        ErrorDocument: 'index.html'
        IndexDocument: 'index.html'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7aafd357-fcf3-4660-b207-84b6cc696b0c
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BucketHost
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${BucketHost}/*'
            Principal: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c0fc79f2-0397-4704-9841-48453b668bb4
  PublishUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub 'user-publish-to-${BucketHost}'
      Policies:
        - PolicyName: !Sub 'policy-publish-to-${BucketHost}'
          PolicyDocument:
            Statement:
            - Action:
                - 's3:ListBucket'
                - 's3:ListObjectsV2'
                - 's3:PutObject'
                - 's3:GetObject'
                - 's3:DeleteObject'
              Effect: Allow
              Resource:
              - !Sub 'arn:aws:s3:::${BucketHost}'
              - !Sub 'arn:aws:s3:::${BucketHost}/*'
  PublishCredentials:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref PublishUser
Outputs:
  Bucket:
    Description: 'S3 Bucket Host'
    Value: !Ref BucketHost
  BucketUrl:
    Description: 'S3 Bucket Url'
    Value: !GetAtt 'BucketHost.WebsiteURL'
  AccessKeyId:
    Description: 'S3 Access Key'
    Value: !Ref PublishCredentials
  AccessKeySecret:
    Description: 'S3 Secret Key'
    Value: !GetAtt PublishCredentials.SecretAccessKey